import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
});

const folito = localFont({
  src: [
    {
      path: "../../public/font/Folito-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/font/Folito-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/Folito-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/font/Folito-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/font/Folito-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-folito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} ${folito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
